### ISSUE TITLE
Defining an array as an environment variable in Kubernetes.

### ISSUE THREAD

**Issue by fourtimes** [operation-unknown/proof-of-concepts#12]
1. Create the Kubernetes environment variable deployment YAML file.
2. Validation of process

**Comment by fourtimes** [comment]
```yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: array
spec:
  replicas: 1
  selector:
    matchLabels:
      app: array
  template:
    metadata:
      labels:
        app: array
    spec:
      containers:
      - name: array
        image: nginx
        env:
        - name: ENV_PROJECTS
          value: "project1,project2,project3"
        ports:
        - containerPort: 80
```
